### ISSUE TITLE
[FEATURE] Allow wash to watch a signed actor for changes

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#105]
**Is your feature request related to a problem? Please describe.**
The current development loop for an actor looks like the following:
1. Generate the actor
1. Change code in the actor
1. run `make build` or equivalent to build and sign actor
1. use `wash reg push` to push the actor to the local registry, at a new tag
1. Launch REPL, run `ctl start actor` to schedule actor
1. Use `call` to invoke operations directly on an actor, or schedule providers, link, and invoke that way
1. Stop actor or relaunch REPL, Repeat from step 2

**Describe the solution you'd like**
This solution is clunky and requires 5 repeated steps to see a code change actually running. There's investigation needed to land on the ideal solution for this problem, but off the top of my head, I see a few possible solutions.
1. `make` step to build, push, and issue `ctl` command to reschedule the actor
2. `wash watch` command, which schedules an actor from a local file and "watches" it for changes, rescheduling the actor when the change occurs
3. `wash ctl start actor <reference> --watch`, which indicates to start monitoring a wasm file for changes

**Additional context**
For 2. #92 will be required in order to watch a local wasm file, but in my opinion this is the best solution out of the three. Watching for rapid changes is a feature that will be useful during development but is unlikely to be used past a local REPL / development environment.

This issue is meant to be a discussion, and I'd love to hear any additional thoughts here on what would make the development experience best. The ideal solution would be a "hot reloading" development environment for the wasmcloud actors.

**Comment by brooksmtownsend** [comment]
Another option could be a VSCode extension that, on save, rebuilds, resigns, and reschedules an actor on a running local wasmcloud host. This ties us to VScode if we only do the extension, but it might be able to tie into any work that we do here in order to support different IDEs and have an ideal experience

**Comment by autodidaddict** [comment]
One thought here is that multiple watches might be used by the same developer on the same workstation. I think we'll want to make sure that all of the following activities re-use the same `wasmcloud` host process:
* watch an actor
* start an actor
* start/stop capability provider
* link provider
* launch the repl via 'up'

In other words, in each case when the tooling goes to issue a command of some kind to a locally running host, it should check if there's already one running and use that, otherwise spin up a new one. I don't know if this means that `wash` should simply spawn a `wasmcloud` host in daemon mode or something more involved.

Put another way, I think the scenario we want to avoid is where a developer starts an actor with "watch", and then in another terminal window starts a capability provider, and then tries to establish a link and can't because they're working with two separate host processes and there's no lattice enabled by default.

Another caveat:
Different operating systems have different levels of and support for file watching. We'll want to keep an eye out for this in case we need to bail and resort to something like timed polling if the underlying OS doesn't support "real" watches for file changes. I've also encountered other scenarios in the past where different operating systems record changes differently. For example, if a process like a compiler writes a new `.wasm` file as a result of compilation, if that file handle was already open by a monitor, the monitor might not be notified. We can see this kind if disparity sometimes in how VSCode behaves with interactions with the file system that don't agree between the IDE and terminal windows.
