### ISSUE TITLE
[BUG] Cache doesn't get cleared when you push and start a new image (actor or capability provider)

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wash-archive#108]
Edit actor source, compile to wasm, push to local registry, start in wasmcloud, - but it's still the old code running! 
You expect your changes to go live but the old code is still running. The problem exists for both actors and capability providers. 

I thought it might be version/revision specific, so I tried bumping the revision. That didn't work. (procedure: stop the old actor, rebuild/sign with new version, push, start) - still get old code. Note that the keys haven't changed.

I thought it might be a problem with the docker oci registry or nats cache, so I tried shutting everything down and starting fresh with an empty registry and clean wasmcloud and clean nats - still get old code.

I had just switched to using a mac two days earlier, since the keyboard on my linux laptop got flakey, and I started to wonder if there was a bug in macos related to file system caching. I made sure I was at the latest version and rebooted.  Added 'sync' commands to my Makefiles, but those things didn't help.

Finally I stumbled onto 'wash drain' - I had seen it in the command help list but hadn't really paid attention since you're usually reading help trying to solve a specific problem. 'wash drain' definitely fixed it. So I've added wash drain to my build script so I can be sure I always get the new code image, but I assume that's probably overkill and I don't know how to fine-tune the cache clearing.

Is there a middle ground, where pushing a new binary image only clears just the relevant parts of the cache? For example,
- If the release number changes, always throw away cached binaries
- if the release number hasn't changed, but the file's sha256 sum has changed, clear cache for previous images. If you are worried about sha256 taking too long, even file modification date and size would fix 99% of the scenarios you would hit during iterative development.

I'm guessing that the 'primary key' in the cache is the actor's public key, which doesn't have any version information in it. So I suppose I could regenerate keys with each build iteration, but I haven't tested to see if that's any faster than purging the cache with 'wash drain'. But it seems like too much of a hack.

It turns out there was another bug in wasmcloud's nats caching (confirmed by Kevin) that I kept hitting that made it seem more complicated and took me longer to figure out.

Other things to consider (not as important as flushing the cache at the right time, but possibly useful)
- If you can't easily flush the relevant parts of the cache automatically, could you create a 'wash' command that I could add to build script or Makefile  (or extra flags on  'wash reg push' perhaps) that could delete caches related to that file?
- It might be useful to have more visibility into what is in the cache, perhaps by listing items in it, to make it easier to decide if it makes sense to purge the whole thing instead of selectively removing certain items.

In case it helps:
- OS: MacOS Big Sur
- Rust stable (1.50) and nightly (1.52) - both experienced the problem

**Comment by autodidaddict** [comment]
This is an interesting bug because I think the solution might be a small one, even though this affects a few areas. 

First and foremost,  wasmcloud considers the binary for a module to be immutable. If you need to update an actor,  it must have a higher revision. 

What I think is happening is a few assumptions made in the code that I can check and confirm once I get to a computer.

**Comment by brooksmtownsend** [comment]
I think the issue here is that we assume our OCI references to be immutable and we cache them, e.g. if you push your local actor to `localhost:5000/myactor:0.2.0`, change it, and then overwrite the same OCI reference with the new actor, our caching logic will simply pull that from cache instead of redownloading. 

`wash drain` is certainly the command you're looking for, however with the recent merge of #122 , you can now load actors from a local wasm file. Only the `start actor` command is supported currently, but I think what would really help this issue is if the `update actor` command ALSO supported local files. This would prevent caching on the OCI side of things, and for local development, we want to remove the registry as part of the feedback loop.

Curious on your thoughts @stevelr, but I think these options will solve the issue:
1. Using `wash drain` in tandem with the same OCI reference
2. Using separate OCI references for each build+push (not ideal)
3. For local developer feedback, skip the registry altogether and instead use the local file instead

**Comment by autodidaddict** [comment]
the underlying assumption that the bytes of a tagged OCI image are immutable is indeed at the heart of this. If those bytes are mutable, then there are security problems that exist far beyond what wasmCloud touches. sorry I didn't reply to this earlier, Github is not ideal for reminding me of issues I need to circle back around to.

**Comment by autodidaddict** [comment]
> 3. For local developer feedback, skip the registry altogether and instead use the local file instead

I think this makes the most sense. For the development iteration cycle where you want rapid feedback, the production-grade concerns of an immutable OCI registry are more hindrance than help... so just using raw files is preferable... and this feature was not available at the time this bug was filed.

**Comment by stevelr** [comment]
I agree that 1 and 2 for every build iteration, aren't ideal. 

I had wondered whether it would be possible to add an optional arg to 'wash drain' to remove just one specific cached actor or provider.

Having 'update actor' load from file would also be a useful work-around for this issue, if it had the side effect of updating the cache. If you don't clear the old image from the cache, you would still have the same problem, because after restart of wasmcloud, you might still get the old image.

Separately, I think making 'update actor' load from disk might be required for making the intent of #122 (running without a registry) complete.

Assumption: This should only work if the signing key is the same as the one used for starting the actor. Otherwise it would be a security risk if someone who didn't have the key could replace an actor in a running system. (This should apply to actors loaded from registries too)

**Comment by autodidaddict** [comment]
"Update actor" would utilize the existing "live update" functionality, which checks that the new and old actors were signed and issued by the same entity, that the new one is a higher revision number and, when strict checking is enabled, has exactly the same list of capabilities.

**Comment by stevelr** [comment]
so are you saying `wash update actor`, loading from disk, with same version and revision number wouldn't work - that a developer has to bump either the version or the revision with every build?

**Comment by brooksmtownsend** [comment]
> so are you saying `wash update actor`, loading from disk, with same version and revision number wouldn't work - that a developer has to bump either the version or the revision with every build?

Correct, if you want to use the `update` feature we have a strict requirement that the `revision` number is greater than the previous version. You can `stop` and `start` the actor if you don't want to bump the revision. This isn't a `wash` requirement/enforcement, it's done so on the wasmcloud-host side.

**Comment by stevelr** [comment]
should `wash sign` have a flag that uses utc timestamp as the revision number? Should that be the default if --revision isn't specified? (the justification for it being the default is to help novice developers avoid this problem )

**Comment by autodidaddict** [comment]
We're looking at having wash auto increment the revision if it discovers a
previous one.

**Comment by brooksmtownsend** [comment]
Yeah with the `watch` feature, it would enable you to watch an actor module for changes, automatically re-signing with an updated revision and updating the actor. It would be used for rapid development, and possibly combined with a build-on-save system in your IDE it would essentially hot-reload your actor.

**Comment by brooksmtownsend** [comment]
@stevelr does #134 resolve your issue here? I'm interpreting the core of the problem as the difficulty in continuously modifying actors, which `wash up --watch` addresses

**Comment by autodidaddict** [comment]
This applies to old codebase (pre-0.5). Closing.
