### ISSUE TITLE
[FEATURE] Show Actor and Provider name on host inventory screen

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#114]
**Is your feature request related to a problem? Please describe.**
The current host inventory looks like this:
![image](https://user-images.githubusercontent.com/12040685/112885530-e10ead00-909e-11eb-926b-97afa3a833d3.png)
This inventory looks great, but notice that actors and providers are only human-identifiable by their OCI reference. Actors and providers that are loaded as static plugins or directly from disk do not show OCI references. This causes a frustrating experience for both of those scenarios.

**Describe the solution you'd like**
The host inventory output should also show the `Name` field of the embedded claims, as the provider and actor claims both have this field. Before the host inventory will have access to this information, https://github.com/wasmCloud/wasmCloud/issues/24 must be completed.

**Additional context**
The host inventory output is already exceeding the width of an average terminal. With the addition of the `Name` column, we'll be even further off the screen if someone is developing on a smaller screen, or with a vertical monitor setup for example. This will need to be addressed.

Some potential solutions:
1. In tandem with #74 , we could show the first 5-10 characters of the public keys and allow for tab completion to fill out the public key. In the above example, if you were linking the HTTPSERVER provider, you could type `VAG3Q<tab>` and the rest of the provider key could autofill.
2. Omit certain fields (IDs, OCI reference) by default, but show indicator in UI that implies more information that can be accessed with additional flags

**Comment by frigus02** [comment]
Hi there. I think showing the actor and provider names would be really useful. I thought I might give this a go and would like to clarify a few things.

- All tables have a max column width at the moment, including the host inventory table:
  
  https://github.com/wasmCloud/wash/blob/31b7c49531c2300f2f421955f8cd5a35d7af0cc3/src/ctl/output.rs#L202

  This sets the width per column. This table has 4 columns, so the max table width is 320. Was this intentional or should the total table width default to 80 instead?

- I noticed that the max column width is never actually specified, so it always uses the default of 80.

I tried to see what the tables look like if we would specify the width so that the entire table max width is equal to the available output width. This is the result (columns that exceed the width, break into multiple lines):

![image](https://user-images.githubusercontent.com/3579251/120829830-c3a20780-c555-11eb-8138-148ac312ecb6.png)

Would you be interested in a PR just for that (restraining the table width to the available output width)?

And then following that, would the line break behavior inside a column be good enough for adding a column for the actor/provider name? Or would you prefer if one of the solutions mentioned above (show only the first few characters of the public key or hide some columns by default) was implemented first?

**Comment by brooksmtownsend** [comment]
Thanks for taking a look @frigus02 ! And good catch on the max width. I think it should definitely be changed to the max _table_ width not the max _column_ width. I'd definitely entertain a PR for that, as long as it looks okay in different scenarios. It's important with the table to be able to easily copy that long ID, which is also the hardest part of conforming to the width.

Following that, I think an MVP would be to show only the first ~5-8 characters of the actor ID, followed by an ellipses (`...`), to show that there's more information. Perhaps the `--output` flag can add another option for `--output wide`, similar to how `kubectl` works. That should give enough screen space to show the Actor/Provider Name in there as well. Tab completion would be nice, but I don't feel like that has to be done all at once to get started on this issue. Also worth mentioning that tab completion would be a bit more complex, as it would likely require some manual work to cache the public keys in order to make tab completion work.

Let me know if you have any other questions, and feel free to start a PR once you have something working and we can iterate off of that, the code doesn't have to be perfect.
