### ISSUE TITLE
[FEATURE] Ability to consume manifest file directly

### ISSUE THREAD

**Issue by snnsnn** [wasmCloud/wash-archive#116]
**Is your feature request related to a problem?

Linking actors and capabilities via command-line is definitely practical but a bit tedious and hard. Bootstrapping REPL environment via manifest file can save time and reduce friction.

**Comment by autodidaddict** [comment]
I'm not sure I follow what you're looking for. I believe we can load/apply a manifest while inside the REPL, right @brooksmtownsend ?

**Comment by brooksmtownsend** [comment]
Actually atm we don't have the ability to start with or apply a manifest @autodidaddict. I'm not sure if applying a manifest while inside of the REPL would be used all that much (especially because a host needs to load it from the beginning) but we should definitely include the ability to run something like:
```
wash up --manifest demo.yaml
# or
wash up -m demo.yaml
```
So that your REPL environment starts with some resources

**Comment by snnsnn** [comment]
> wash up --manifest demo.yaml

This is exactly what I meant.

**Comment by autodidaddict** [comment]
I like the idea of being able to bootstrap your REPL with a manifest.

**Comment by brooksmtownsend** [comment]
Adding `good first issue` as this would be a great place to start!
