### ISSUE TITLE
[FEATURE] `wash install`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#264]
**Is your feature request related to a problem? Please describe.**
Installing the wasmCloud host isn't necessarily difficult, but could be much easier.

**Describe the solution you'd like**
In tandem with https://github.com/wasmCloud/wasmcloud-otp/issues/395, it would be great for our initial user install to be able to download `wash`, run `wash install`, and automatically have the NATS and wasmCloud binaries downloaded to something like `~/.wash/bin`. This is a familiar install process to other tools, and makes the initial setup of a wasmCloud developer environment easy and simple.

Installing NATS could certainly be an optional flag, as that's not always the desired action for the user. One thing I despise about `brew` for example is that `brew install wash` can also end up installing another Rust toolchain which can be confusing, and this process should not mess with a developer's environment by default.

**Comment by ghost** [comment]
`brew install wash` can install another Rust toolchain? That's really odd, does brew build from source? I always thought it just served the binary.

Anyway, instead of `wash install`, should we have something like `rustup`? Which just installs everything you need for wasmCloud development (wash, nats, wasmcloud) all at once? `washup`? lol

Then we can do something similar to `rustup`'s website: https://rustup.rs/

**Comment by brooksmtownsend** [comment]
> does brew build from source? I always thought it just served the binary.

Only if it can't find a binary, which we may not actually upload 🤔 But it installs the dependent packages anyway I believe

I'm fine with a rustup-y type script or like get.crit.sh, I'd only want to ensure that it's easy to maintain, my biggest concern is simply that we'd want some kind of `wash upgrade` or `wash install --upgrade` to update dependencies
