### ISSUE TITLE
[FEATURE] wash contexts should be able to be referenced by name instead of path

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wash-archive#270]
**Is your feature request related to a problem? Please describe.**
When you provide a `--context` flag, it expects the value to be the full path to a context file. This is confusing because we have named contexts available, and it would be easier to be able to load them by name similar to how `kubectl` handles it.

**Describe the solution you'd like**
The `--context` flag should load contexts by name instead of by path.

**Comment by brooksmtownsend** [comment]
I think I did this so that you could specify a context file not under `~/.wash/contexts`, though I agree that the context should be specified with a name and an option like that could be `--context-path` or to specify a `--context-dir` or something like that.

Just in case that was unclear, totally in favor of this 👍🏻
