### ISSUE TITLE
[BUG] Problems generating a new project for tinygo

### ISSUE THREAD

**Issue by gmlewis** [wasmCloud/wash-archive#291]
**Describe the bug**
I was following the "Getting started" tutorial here: https://wasmcloud.dev/app-dev/create-actor/generate/
I clicked on the "TinyGo" tab and ran the first command, but it fails.

**To Reproduce**
1. Run command `wash new actor hello --template-name echo-tinygo`
2. See error:

```bash
⛔   Git Error: authentication required but no callback set; class=Ssh (23); code=Auth (-16)
```

**Expected behavior**
I expected a new project directory to be created.

**Screenshots**
![ksnip_20220719-101133](https://user-images.githubusercontent.com/6598971/179771543-3740f37f-3d6c-474c-b5da-1a185f06fdc3.png)

**Environment (please complete the following information) **
 - OS: Linux Mint Cinnamon 20.3
 - Shell: bash
 - wash Version: 0.11.0

**Comment by brooksmtownsend** [comment]
@gmlewis real quick check, do you have openssl installed on your machine? That's one library that `wash` attempts to dynamically link to for the time being in order to clone the project-templates repository

**Comment by gmlewis** [comment]
_taking this offline to Slack..._

**Comment by brooksmtownsend** [comment]
Updates from the Slack back-and-forth:

After a bit of digging and launching a Linux Mint 20.3 VM, I wasn't able to reproduce with the following script:
```bash
#!/bin/bash
apt update
apt install build-essential libssl-dev vim curl pkg-config -y
# curl script to install rust
source "$HOME/.cargo/env"
cargo install wash-cli
wash new actor hello --template-name echo-tinygo
```

It appears that something about git is expecting SSH authentication even though it's a public repository. As a workaround the fix was simply to clone the repository using the installed `git` and then generate the project from there:
```
git clone https://github.com/wasmCloud/project-templates.git
wash new actor --path project-templates/actor/echo-tinygo hello
```

If someone else is able to reproduce that would be very helpful, for now the workaround is a temporary step. This may be resolved if we change the git implementation to use `rustls` just because of different implementation details.

**Comment by gmlewis** [comment]
@brooksmtownsend and I discovered that the culprit was in my `~/.gitconfig` file.  Specifically, if I comment out these two lines:

```
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

everything works great.  Thank you for your patience and assistance, @brooksmtownsend !  I appreciate it!

**Comment by luebken** [comment]
I ran into the same problem. The git clone workaround by @brooksmtownsend worked for me.

**Comment by brooksmtownsend** [comment]
@luebken Did you have anything special in your `~/.gitconfig` file?

**Comment by luebken** [comment]
Circling back from Slack: commenting out the following lines fixed it for me: 
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```
