### ISSUE TITLE
[FEATURE] Wash should detect unusable imports/generated code at compile-time

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wash-archive#343]
**Is your feature request related to a problem? Please describe.**
Currently, it's possible to compile and sign actor modules which include code that will panic at runtime, e.g. trying to access time from a Rust actor, or IIRC, JSON marshalling in Go

**Describe the solution you'd like**
Assuming there are clear signs an actor will panic at runtime, `wash` should be able to inspect the generated wasm module and emit an error to the user stating as such

**Describe alternatives you've considered**
N/A

**Additional context**
Here's an example of a `wat` file for an actor that imports and tries to use `chrono`:
```
  (import "__wbindgen_placeholder__" "__wbindgen_object_drop_ref" (func $_ZN12wasm_bindgen26__wbindgen_object_drop_ref17ha1d0e8a0346b8e68E (type 0)))
  (import "__wbindgen_placeholder__" "__wbindgen_describe" (func $_ZN12wasm_bindgen19__wbindgen_describe17h7235a65d87e07d3aE (type 0)))
  (import "__wbindgen_placeholder__" "__wbg_getTime_58b0bdbebd4ef11d" (func $_ZN6js_sys4Date8get_time30__wbg_getTime_58b0bdbebd4ef11d17ha181626b416646adE (type 14)))
  (import "__wbindgen_placeholder__" "__wbg_new0_adda2d4bcb124f0a" (func $_ZN6js_sys4Date5new_027__wbg_new0_adda2d4bcb124f0a17hbf83f9a0526ddb8cE (type 13)))
  (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_grow" (func $_ZN12wasm_bindgen9externref31__wbindgen_externref_table_grow17h3a0263ad1291b191E (type 1)))
  (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_set_null" (func $_ZN12wasm_bindgen9externref35__wbindgen_externref_table_set_null17h4816c9fdd04efdbfE (type 0)))
  (import "__wbindgen_placeholder__" "__wbindgen_throw" (func $_ZN12wasm_bindgen16__wbindgen_throw17habeb0379de2ba276E (type 10)))
```

Assuming this is a Bad Sign ™️, `wash` should be able to detect this and let the user know it's Bad ™️

**Comment by ghost** [comment]
What's the problematic part of that file exactly? I'm assuming it's this line:
```
(import "__wbindgen_placeholder__" "__wbg_getTime_58b0bdbebd4ef11d" (func $_ZN6js_sys4Date8get_time30__wbg_getTime_58b0bdbebd4ef11d17ha181626b416646adE (type 14)))
```

So the implementation of this could be a regex that scans for `getTime` in the `wat` file post compilation? Or should this be a level up where we have a list of packages that aren't compatible and `wash build` checks for those before compiling?

**Comment by stevelr** [comment]
@mattwilkinsonn the problem is that wasm built for a browser with wasm-bindgen often has a bunch of import dependencies that are only available in a browser wasm runtime. When any "host" (browser, or server-side process that runs wasm) loads a webassembly module, the imports in the module are matched to exports of the host. If there are imports that don't have a matching export, loading fails.

A wasmcloud compatibility tool would check that the wasm imports and exports are compatible with the [wasmCloud host ABI](https://wasmcloud.dev/reference/wasmbus/ffi/), and would give an error for any missing exports, or excess imports that aren't supported by the host
