### ISSUE TITLE
[BUG] WASMCLOUD_VERSION doesnt like rc tags

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wash-archive#374]
**Describe the bug**
When using `WASMCLOUD_VERSION` to have `wash up` use .60-rc8....it gets unhappy.
```
#9 7.489 wasmCloud version v0.60.0-rc.8 is earlier than the minimum supported version of v0.57.0
```

**To Reproduce**
1. `WASMCLOUD_VERSION=v0.60.0-rc.8 wash up`

**Comment by thomastaylor312** [comment]
I am pretty sure this is because rc tags are technically not "newer" as defined by the semver spec. We might need to do some custom handling for this. But it could also be due to the `semver` crate in Rust. Still digging into it

**Comment by thomastaylor312** [comment]
Yep, I think it is due to a misleading error message. I don't think it thinks it is earlier, but the version selector used in the [`check_version`](https://github.com/wasmCloud/wash/blob/01ad509c36663bc87ce00185f96494122ea4a985/crates/wash-lib/src/start/wasmcloud.rs#L314) function doesn't allow it to select an RC. I think what is needed is just to compare that the version passed is later rather than using a requirement selector

**Comment by jordan-rash** [comment]
Thanks Taylor! :-)
