### ISSUE TITLE
Wash up windows 10 error

### ISSUE THREAD

**Issue by ldariom** [wasmCloud/wash-archive#632]
**Describe the bug**

Hello good, I have a question when installing it in windows with choco I get the following error:

wash up --detached
`
Failed to request release tarball: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/nats-io/nats-server/releases/download/v2.9.14/nats-server-v2.9.14-windows-amd64.tar.gz", query: None, fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) } }) }`

How do I get up the wasmCloud user interface?

**To Reproduce**
1. install wash with choco
1. Run wash up --detached
1. See error

**Expected behavior**
raise the environment 

**Screenshots**
<img width="482" alt="image" src="https://github.com/wasmCloud/wash/assets/14187352/c2c441fa-3395-43ef-831a-4b79e323b745">

**Environment (please complete the following information) **
 - OS: Windows
 - Cmd
 - wash 0.18.0

**Comment by brooksmtownsend** [comment]
Hey @ldariom, thanks for filing this issue. I'll see if I can reproduce on my Windows machine, that issue seems to point to either a temporary downtime for GitHub or missing ca-certificates 🤔 
```
InvalidData, error: InvalidCertificate(UnknownIssuer)
```

The URL looks correct at least, that version of NATS should be good. I'm not a daily Windows user, do you know of a package on chocolatey to install the Windows equivalent of the Linux package ca-certificates?
