### ISSUE TITLE
cursor can be in wrong position after resize

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wash-archive#90]
I use a tiling window manager and often move a window from small to full screen and back to small again. In wash, sometimes if I resize the window larger or smaller, the REPL cursor appears a line above or below the line where you would type the next command. It turns out that if the REPL window has had any wrap-around (such as with a 'ctl get inventory -long id-'), where the command wraps onto the second line, and then resize larger so that the command fits on one line, the cursor is drawn one line too low. It's as if it remembered the y position from before the resize and didn't recalculate it after the resize. If you go the other way around - long command on large window, then  shrink the app window so wrap is required, the cursor is one line too high.

After a brief search about tui resizing, I tried adding "terminal.autoresize()?;" at the beginning of draw_ui, but that didn't fix it. If you type "clear" in the REPL window, it does clear and the cursor position is in the correct place.

Not a high priority bug as it doesn't affect functionality, and using the "clear" command is a workaround.

**Comment by brooksmtownsend** [comment]
We calculate the position of the cursor semi-manually by using the width of the input pane and the amount of characters type so far to know when to wrap down to a lower line. It seems that terminal resizing does not trigger any recalculation in this cursor position, so I wonder if there's a resize event with Tui that we can use to recalculate the cursor position as that occurs. Here's the function that calculates the tuple (x_position, y_position) of the input cursor: https://github.com/wasmCloud/wash/blob/main/src/up.rs#L165. In order to calculate the correct position, I think we will need to assign the new input pane width to the `input_width` field, then it should move the cursor to the correct place

**Comment by brooksmtownsend** [comment]
This is all just to document where I think I can fix the issue, but if anyone looks at this as a start to contribute before I get here I wanted to provide some context 😄

**Comment by brooksmtownsend** [comment]
From #95 , I've added in a few
```
//TODO(issue #90):
```
snippets in the code, refer to these if looking to tackle this issue
